export enum EnvVariable {
  NEXT_PUBLIC_GRAPHQL_ENDPOINT = "NEXT_PUBLIC_GRAPHQL_ENDPOINT",
  NEXT_PUBLIC_EMAIL_AUTH_ENDPOINT = "NEXT_PUBLIC_EMAIL_AUTH_ENDPOINT",
  NEXT_PUBLIC_GOOGLE_AUTH_ENDPOINT = "NEXT_PUBLIC_GOOGLE_AUTH_ENDPOINT",
  NEXT_PUBLIC_INSTAGRAM_AUTH_ENDPOINT = "NEXT_PUBLIC_INSTAGRAM_AUTH_ENDPOINT",
  NEXT_PUBLIC_FILE_ENDPOINT = "NEXT_PUBLIC_FILE_ENDPOINT",
  NEXT_PUBLIC_BASE_URL = "NEXT_PUBLIC_BASE_URL",
  REFRESH_KEY = "REFRESH_KEY",
  SIGNING_KEY = "SIGNING_KEY",
  INSTAGRAM_CLIENT_SECRET = "INSTAGRAM_CLIENT_SECRET",
  INSTAGRAM_CLIENT_ID = "INSTAGRAM_CLIENT_ID",
  GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET",
  GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID",
  TURNSTILE_KEY = "TURNSTILE_KEY",
  AWS_ACCESS_KEY_ID = "AWS_ACCESS_KEY_ID",
  AWS_ACCESS_KEY_SECRET = "AWS_ACCESS_KEY_SECRET",
  AWS_REGION = "AWS_REGION",
  AWS_BUCKET = "AWS_BUCKET",
  NODE_ENV = "NODE_ENV",
}

export function getEnv<T extends boolean = false>(
  key: EnvVariable,
  skipCheck?: T,
): T extends true ? string | undefined : string {
  const value = process.env[key];
  if (!skipCheck && !value) throw new Error(`${key} is not defined`);
  return value as T extends true ? string | undefined : string;
}
